### ISSUE TITLE
Allow document body scroll

### ISSUE THREAD

**Issue by apod42** [HTMLGuyLLC/jAlert#27]
Hello! When an alert pops-up, the vertical scrollbar is hidden and page body is no longer scrollable. Any way to prevent this behaviour? In the plugin options have found nothing related... Thank you!

**Comment by HTMLGuyLLC** [comment]
So you want the popup to display with the black background, but the regular
page to be scrollable as well?

**Comment by apod42** [comment]
I don't want any overlay (black background) to be displayed over the page. And yes, the regular page should be scrollable. Any way to do this please?

**Comment by HTMLGuyLLC** [comment]
Do you also want the alert to be movable?

**Comment by apod42** [comment]
Shane, no, I don't want the alert to be movable. Just to keep centered on page resize, as it does now.

Emil

**Comment by HTMLGuyLLC** [comment]
I'm just trying to fully understand what you're looking for so that I can decide if it's a useful feature to add for everyone, or too specific of a use-case. I could see it being a desired feature to say "Ok, I want a popup that doesn't cover any content. One that people can move around to see what's underneath" (for instance, this could contain an editable field and maybe you need to refer to the page's content to fill it in), but to just have one that sits in the middle over stuff while you scroll sounds too specific for most people to want..so instead of making that a feature of the plugin, I'll just tell you how to do it for your implementation. One moment.

**Comment by HTMLGuyLLC** [comment]
Comment out line 280 of jAlert-v3.js
//$('body').css('overflow', 'hidden');

That might be all you need to do. I can't test right now, but let me know if that works. Since you didn't ask about the background, I'm assuming you already removed that on your own?

**Comment by apod42** [comment]
Thank you, works great! Now I just need to get rid of the background, please do tell :)

**Comment by HTMLGuyLLC** [comment]
2 Options:

1:
Comment out line 131 of jAlert
//backgroundClasses.push('ja_wrap_'+thisAlert.options.backgroundColor);

2:
Pass a bunk background color like pink
$.jAlert({
'title':'Hi',
'content':'Sup?',
'backgroundColor':'pink'
});

**Comment by HTMLGuyLLC** [comment]
Scrap that. The second one won't work because it validates the background color. You'd have to also add it to the backgroundColors array.

**Comment by HTMLGuyLLC** [comment]
Just comment out line 131 of jAlert.js. lol.

**Comment by apod42** [comment]
Thank you! Great success :)

**Comment by HTMLGuyLLC** [comment]
No problem :)
